fh=open("output.txt","w+t")
a=input("enter the data to be written on the file :")
fh.write(a+"\n")
print("Data successfully written on the file :")
b=input("enter the data to be appended on the file")
fh.write(b)
print("Data successfully written on the file")
print("the file content of the file is :")
fh.seek(0)
print(fh.readline())
print(fh.readline())

fh.close()
